name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven
        run: |
          ls -a
          mvn -B package --file pom.xml
          ls -a
  
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with maven
        run: |
          pwd
          ls -a
          mvn clean test
          ls -a
  
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: second run
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with Maven
        run: |
          pwd
          ls -a
          mvn clean test
          ls -a
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git add screenshots
          git config --global  user.email "my-bot@gmail.com"
          git config --global  user.name  "mybot"
          git commit -m " commit screenshots "
          git push origin v1
        
        
        
